
export default {
    // count
    INCREMENT_COUNT: "INCREMENT_COUNT",
    DECREMENT_COUNT: "DECREMENT_COUNT",
    RESET_COUNT: "RESET_COUNT",
    
    // characters
    GET_CHARACTERS: "GET_CHARACTERS",
    ADD_CHARACTER: "ADD_CHARACTER",
    REMOVE_CHARACTER: "REMOVE_CHARACTER",
    REMOVE_CHARACTERS: "REMOVE_CHARACTERS",
    
    // characterDetail
    GET_CHARACTER_DETAIL: "GET_CHARACTER_DETAIL",
    REMOVE_CHARACTER_DETAIL: "REMOVE_CHARACTER_DETAIL",
}